name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: n1hility/cancel-previous-runs@v2
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout another repo
      uses: actions/checkout@v2
      with:
        repository: 'w311ang/checkHash'
    - name: Test checkout
      uses: actions/checkout@v2
      with:
        repository: 'w311ang/pytools'
        path: './pytools'
      run: |
        cp ./pytools/pytools.py .
        ls

