name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout another repo
      uses: actions/checkout@v2
      with:
        repository: 'w311ang/checkHash'
    - name: Test checkout
      uses: actions/checkout@v2
      with:
        repository: 'w311ang/pytools'
        path: './pytools'
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 60
