name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test checkout
    - uses: actions/checkout@v2
      with:
        repository: 'w311ang/pytools'
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 60
